/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package harpi.alpha;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import harpi.alpha.dice.DiceRoller;
import harpi.alpha.music.MusicPlayer;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.utils.cache.CacheFlag;

public class App {
    final static Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) throws Exception {
        String token = args.length >= 1 ? args[0] : System.getenv("DISCORD_ID");

        if (token == null) {
            System.out.println(
                    "Please provide a token as the first argument or set the DISCORD_ID environment variable.");
            return;
        } else {
            System.out.println("Using token: " + token);
        }

        logger.info("Starting harpi...");

        CommandHandler commandHandler = new CommandHandler();
        MusicPlayer musicPlayer = new MusicPlayer();
        commandHandler.registerCommand(new DiceRoller());
        musicPlayer.registerCommands(commandHandler);

        JDABuilder.createDefault(token, GatewayIntent.getIntents(GatewayIntent.ALL_INTENTS))
                .addEventListeners(commandHandler)
                .setActivity(Activity.watching("você!"))
                .enableCache(CacheFlag.VOICE_STATE)
                .build();
    }
}
